using System.Text;
using Microsoft.Extensions.Options;
using TaskAutomation.Application.Configuration;
using TaskAutomation.Application.Services;
using TaskAutomation.Domain.Models;

namespace TaskAutomation.Infrastructure.Services;

public sealed class MarkdownCommentFormatter(IOptions<WorkflowOptions> workflowOptions) : ICommentFormatter
{
    public TaskCommentPayload Build(WorkItemSnapshot workItem, WorkItemAnalysisResult analysisResult)
    {
        var signature = $"[TaskAutomation:{workItem.Id}:rev:{workItem.Revision}]";
        var builder = new StringBuilder();

        builder.AppendLine("## AI task analysis");
        builder.AppendLine();
        builder.AppendLine($"**Summary**");
        builder.AppendLine();
        builder.AppendLine(analysisResult.Summary);
        builder.AppendLine();
        builder.AppendLine("**Implementation notes**");
        builder.AppendLine();
        builder.AppendLine(analysisResult.ImplementationNotes);
        builder.AppendLine();
        AppendList(builder, "Impacted areas", analysisResult.ImpactedAreas);
        AppendList(builder, "Risks", analysisResult.Risks);
        AppendList(builder, "Suggested tests", analysisResult.SuggestedTests);
        builder.AppendLine($"_Generated by {workflowOptions.Value.ServiceSignature} via {analysisResult.Provider}_");
        builder.AppendLine(signature);

        return new(builder.ToString().Trim(), signature);
    }

    private static void AppendList(StringBuilder builder, string title, IReadOnlyList<string> items)
    {
        if (items.Count == 0)
        {
            return;
        }

        builder.AppendLine($"**{title}**");
        builder.AppendLine();

        foreach (var item in items)
        {
            builder.AppendLine($"- {item}");
        }

        builder.AppendLine();
    }
}
